# Usa Node.js como base
FROM node:20-alpine

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar todo el código
COPY . .

# Exponer el puerto del server (ej: 5000)
EXPOSE 5000

# Comando para arrancar el server
CMD ["npm", "start"]
