#version: '3.8'

services:

  db: 
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: practicasPascualinas
    volumes:
      - backUpPracticasPascualinas:/var/lib/postgresql/data
      - ./server/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
          
  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile.server
    container_name: node_server
    ports:
      - "5000:5000"
    develop: #para actualizar el contenedor cada vez que se guarde un cambio en el IDE
      watch:
        - path: .
          action: rebuild
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
      - hojasDeVidaStorage:/app/uploads/hojas_de_vida
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
    container_name: react_client
    ports:
      - "5173:5173"   # el 3000 local va al 80 del contenedor
    develop: #para actualizar el contenedor cada vez que se guarde un cambio en el IDE
      watch:
        - path: .
          action: rebuild
    
volumes:
  backUpPracticasPascualinas:
  hojasDeVidaStorage: